In [134]:
# tensorflow + pandas

# pandas는 정형데이터를 취급
import pandas as pd
import tensorflow as tf

In [135]:
# 1. load data

In [136]:
csv_file = tf.keras.utils.get_file('heart.csv', 'https://storage.googleapis.com/applied-dl/heart.csv')
df = pd.read_csv(csv_file)

In [137]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
age         303 non-null int64
sex         303 non-null int64
cp          303 non-null int64
trestbps    303 non-null int64
chol        303 non-null int64
fbs         303 non-null int64
restecg     303 non-null int64
thalach     303 non-null int64
exang       303 non-null int64
oldpeak     303 non-null float64
slope       303 non-null int64
ca          303 non-null int64
thal        303 non-null object
target      303 non-null int64
dtypes: float64(1), int64(12), object(1)
memory usage: 33.3+ KB


In [138]:
# keras classfier로 sklearn의 pipeline을 활용함.

In [139]:
df['thal'] = pd.Categorical(df['thal'])
df['thal'] = df.thal.cat.codes

target = df.pop('target')
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values))


In [140]:
df['thal'].dtypes

dtype('int8')

In [141]:
target = df.pop('thal')

In [142]:
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values))

In [143]:
# dir(dataset.take(5))
for i in dataset.take(5):
    print(i)
    print("@@@@@@@@@@@@@@@@",len(i), "@@@@@@@@@@@@@@@@")

(<tf.Tensor: id=162, shape=(12,), dtype=float64, numpy=
array([ 63. ,   1. ,   1. , 145. , 233. ,   1. ,   2. , 150. ,   0. ,
         2.3,   3. ,   0. ])>, <tf.Tensor: id=163, shape=(), dtype=int8, numpy=2>)
@@@@@@@@@@@@@@@@ 2 @@@@@@@@@@@@@@@@
(<tf.Tensor: id=164, shape=(12,), dtype=float64, numpy=
array([ 67. ,   1. ,   4. , 160. , 286. ,   0. ,   2. , 108. ,   1. ,
         1.5,   2. ,   3. ])>, <tf.Tensor: id=165, shape=(), dtype=int8, numpy=3>)
@@@@@@@@@@@@@@@@ 2 @@@@@@@@@@@@@@@@
(<tf.Tensor: id=166, shape=(12,), dtype=float64, numpy=
array([ 67. ,   1. ,   4. , 120. , 229. ,   0. ,   2. , 129. ,   1. ,
         2.6,   2. ,   2. ])>, <tf.Tensor: id=167, shape=(), dtype=int8, numpy=4>)
@@@@@@@@@@@@@@@@ 2 @@@@@@@@@@@@@@@@
(<tf.Tensor: id=168, shape=(12,), dtype=float64, numpy=
array([ 37. ,   1. ,   3. , 130. , 250. ,   0. ,   0. , 187. ,   0. ,
         3.5,   3. ,   0. ])>, <tf.Tensor: id=169, shape=(), dtype=int8, numpy=3>)
@@@@@@@@@@@@@@@@ 2 @@@@@@@@@@@@@@@@
(<tf.Tensor: id=170,

In [144]:
tf.constant(df['thal'])

KeyError: 'thal'

In [73]:
# tips데이터 labelencoding해보기

import seaborn as sns

tips = sns.load_dataset('tips')

# tips

# category를 캐스팅 --> labelEncoding
def convert_label_encoding(dataDummy, columnsName):
    dataDummy[columnsName] = pd.Categorical(dataDummy[columnsName])
    dataDummy[columnsName] = dataDummy[columnsName].cat.codes
    dataDummy[columnsName] = dataDummy[columnsName].astype('category')
    return dataDummy[columnsName]

for i in ['sex', 'smoker', 'day', 'time']:
    tips[i] = convert_label_encoding(tips, i)

In [74]:
tips

total_bill   tip sex smoker day time  size
0         16.99  1.01   1      1   3    1     2
1         10.34  1.66   0      1   3    1     3
2         21.01  3.50   0      1   3    1     3
3         23.68  3.31   0      1   3    1     2
4         24.59  3.61   1      1   3    1     4
..          ...   ...  ..    ...  ..  ...   ...
239       29.03  5.92   0      1   2    1     3
240       27.18  2.00   1      0   2    1     2
241       22.67  2.00   0      0   2    1     2
242       17.82  1.75   0      1   2    1     2
243       18.78  3.00   1      1   0    1     2

[244 rows x 7 columns]