In [17]:
import seaborn as sns
import numpy as np

In [2]:
iris = sns.load_dataset('iris')

In [3]:
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
iris['sepal_width']

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ... 
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

In [14]:
iris[['sepal_width', 'sepal_length']]

sepal_width  sepal_length
0            3.5           5.1
1            3.0           4.9
2            3.2           4.7
3            3.1           4.6
4            3.6           5.0
..           ...           ...
145          3.0           6.7
146          2.5           6.3
147          3.0           6.5
148          3.4           6.2
149          3.0           5.9

[150 rows x 2 columns]

In [16]:
iris[['sepal_width', 'sepal_length']].mean()

sepal_width     3.057333
sepal_length    5.843333
dtype: float64

In [20]:
np.add.accumulate(iris[['sepal_width', 'sepal_length']])

sepal_width  sepal_length
0            3.5           5.1
1            6.5          10.0
2            9.7          14.7
3           12.8          19.3
4           16.4          24.3
..           ...           ...
145        446.7         851.6
146        449.2         857.9
147        452.2         864.4
148        455.6         870.6
149        458.6         876.5

[150 rows x 2 columns]

In [23]:
np.sin(np.pi)

1.2246467991473532e-16

In [24]:
np.pi

3.141592653589793

In [25]:
np.greater(10, 50)

False

In [26]:
np.greater(502, 10)

True

In [39]:
# broadcasting

# 1.  
np.array([[1,2],[3,4]]) + 1

# 2. shape에 1만 있을경우. 크기 보정
np.array([[1,2],[3,4]]) + np.array([[4,5]])

# 3. 2와는 반대로
np.array([[1,2],[3,4]]) + np.array([[10],[10]])


# example
iris['petal_length'] + 10 # broadcasting

0      11.4
1      11.4
2      11.3
3      11.5
4      11.4
       ... 
145    15.2
146    15.0
147    15.2
148    15.4
149    15.1
Name: petal_length, Length: 150, dtype: float64

In [41]:
# 수동으로 맞춰주는법
a = np.arange(10)

a

a = a.reshape(2, -1) # 모든 음수값은 가능하나 관례상 -1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a.reshape(2, -1) # 모든 음수값은 가능하나 관례상 -1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
a.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a.reshape(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
a = np.arange(10)

In [120]:
# a.resize(2,4)
# a.resize(-1) # 불가
# a.resize(100, 100) # 큰값으로하면 초기화하여 만듬
# a.reshape(1, -1) # 한줄로 만들기(대신에 2차로 됨)

# 한줄로 만드는 방법 3
# a.reshape(10) # 1차원만 넣으면 [[]]가 아니라 []로됨.
# a.ravel() # result same.but, view
# a.flatten() # result same.but, copy

In [124]:
a = a.reshape(2,3,4)

ValueError: cannot reshape array of size 10 into shape (2,3,4)

In [145]:
x = np.array([[[0],[1],[2]]])

In [146]:
x.shape

(1, 3, 1)

In [147]:
x

array([[[0],
        [1],
        [2]]])

In [148]:
x.squeeze() # 1차로 압축

array([0, 1, 2])

In [149]:
x

array([[[0],
        [1],
        [2]]])

In [155]:
x = np.array([1,2])

In [157]:
np.expand_dims(x, 1)

array([[1],
       [2]])

In [158]:
x[np.newaxis]

array([[1, 2]])

In [160]:
x = np.array([[[1,2],[3,4]]])

In [161]:
x

array([[[1, 2],
        [3, 4]]])

In [162]:
x[:,:,0]

array([[1, 3]])

In [166]:
x[..., np.newaxis]

array([[[[1],
         [2]],

        [[3],
         [4]]]])

In [167]:
x

array([[[1, 2],
        [3, 4]]])

In [168]:
b = np.zeros((3,3))

In [169]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [170]:
np.zeros_like(x)

array([[[0, 0],
        [0, 0]]])

In [171]:
np.linalg.inv(x)

array([[[-2. ,  1. ],
        [ 1.5, -0.5]]])

In [173]:
from scipy.stats import norm

In [174]:
dir(norm)

['__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_argcheck',
 '_argcheck_rvs',
 '_cdf',
 '_cdf_single',
 '_cdfvec',
 '_construct_argparser',
 '_construct_default_doc',
 '_construct_doc',
 '_ctor_param',
 '_entropy',
 '_fit_loc_scale_support',
 '_fitstart',
 '_get_support',
 '_isf',
 '_logcdf',
 '_logpdf',
 '_logsf',
 '_mom0_sc',
 '_mom1_sc',
 '_mom_integ0',
 '_mom_integ1',
 '_munp',
 '_nnlf',
 '_nnlf_and_penalty',
 '_open_support_mask',
 '_parse_args',
 '_parse_args_rvs',
 '_parse_args_stats',
 '_pdf',
 '_penalized_nnlf',
 '_ppf',
 '_ppf_single',
 '_ppf_to_solve',
 '_ppfvec',
 '_random_state',
 '_reduce_func',
 '_rvs',
 '_