In [1]:
import seaborn as sns
import numpy as np

In [5]:
a = np.loadtxt('iris.csv', skiprows=1, delimiter=',')

In [13]:
b = np.genfromtxt('iris.csv', skip_header=1)

In [19]:
b

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan])

In [43]:
a = [1,2,3]
with open('sun1.g', 'w') as f:
    f.write('[1,2,3]')

In [44]:
with open('sun.g') as f:
    print(f.readlines())

[]


In [45]:
import pickle

In [48]:
a = [1,2,3,]

with open('sun2.g', 'wb') as f:
    pickle.dump(a, f)

In [49]:
with open('sun2.g', 'rb') as g:
    t  = pickle.load(g)

In [50]:
t

[1, 2, 3]

In [51]:
xx = np.arange(100)

In [52]:
np.save('sun3', xx)

In [93]:
k = np.load('sun3.npy')

In [ ]:
import  as data

In [92]:
k = data.values

NameError: name 'data' is not defined

In [64]:
'1x2x3x4x5x6x'.split('x')

['1', '2', '3', '4', '5', '6', '']

In [68]:
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [69]:
a,b,c = np.split(k, 3) # k를 3등분

ValueError: array split does not result in an equal division

In [71]:
np.split(k, (2,3)) # 2보다 작은범위, 2와 3사이,3보다 큰범위

[array([0, 1]),
 array([2]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
        71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
        88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])]

In [90]:
x, y = np.vsplit(a, 2)

In [74]:
np.hsplit(a, 2)

AttributeError: 'list' object has no attribute 'ndim'

In [75]:
np.dsplit(a, 2)

ValueError: dsplit only works on arrays of 3 or more dimensions

In [83]:
a, b = np.ix_([1,2],[3,4])

In [82]:
a + b

array([[4, 5],
       [5, 6]])

In [80]:
np.expand_dims([1,2], 0)

array([[1, 2]])

In [86]:
np.meshgrid([1,2],[3,4])

[array([[1, 2],
        [1, 2]]), array([[3, 3],
        [4, 4]])]

In [87]:
a, b = np.meshgrid([1,2],[3,4])

In [88]:
a

array([[1, 2],
       [1, 2]])

In [89]:
b

array([[3, 3],
       [4, 4]])

In [96]:
a = np.arange(12).reshape(6,2)

In [97]:
x, y = np.split(a,2)

In [101]:
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [102]:
y

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [103]:
np.r_[x,y] # 합치기!

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [108]:
np.r_[[x],[y]] # 합치기!

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [107]:
np.c_[x,y] # 늘리기?

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [109]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [110]:
a[np.newaxis]

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [111]:
a[np.newaxis, ...]

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [112]:
a[:, np.newaxis]

array([[[ 0,  1]],

       [[ 2,  3]],

       [[ 4,  5]],

       [[ 6,  7]],

       [[ 8,  9]],

       [[10, 11]]])

In [114]:
a[:,:,np.newaxis]

array([[[ 0],
        [ 1]],

       [[ 2],
        [ 3]],

       [[ 4],
        [ 5]],

       [[ 6],
        [ 7]],

       [[ 8],
        [ 9]],

       [[10],
        [11]]])

In [119]:
a = np.array([[1, 2], [3, 4]])

In [120]:
a.shape

(2, 2)

In [121]:
a[np.newaxis].shape

(1, 2, 2)

In [128]:
a[np.newaxis].shape # (2,2) -> (1, 2, 2)

(1, 2, 2)

In [131]:
a[:, np.newaxis].shape # (2,2) -> (2, 1, 2)

(2, 1, 2)

In [135]:
from tensorflow.keras.datasets import mnist;

In [136]:
mnist.load_data()

((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [137]:
(x, y), (a, b) = mnist.load_data()

In [139]:
x.shape

(60000, 28, 28)

In [148]:
x[0, :, :] # x의 첫번째, y,z 전부
x[0, ...] # 축약
x[0] # 생략

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [149]:
a = np.full((28,28),255)

In [152]:
a.shape

(28, 28)

In [153]:
x + a[np.newaxis]

array([[[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       ...,

       [[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255

In [155]:
np.newaxis # None is None , True

In [156]:
a[None] # 가능하되, 단지 헷갈릴 여지때문에 np.newaxis로 함.

array([[[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
         255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
         255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
         255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
         255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
         255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
         255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
         255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
         255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
         255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
         255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
         255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
         255, 255, 255

In [164]:
a = np.genfromtxt('iris.csv', delimiter=',',skip_header=1)

In [168]:
a.shape

(150, 4)

In [169]:
np.concatenate((a,a)).shape

(300, 4)

In [170]:
np.concatenate((a,a), axis=1).shape

(150, 8)

In [173]:
np.vstack((a,a)).shape

(300, 4)

In [174]:
np.hstack((a,a)).shape

(150, 8)

In [175]:
np.dstack((a,a)).shape

(150, 4, 2)

In [176]:
x = np.array([[1,2],[3,4]])

In [177]:
x

array([[1, 2],
       [3, 4]])

In [178]:
np.dstack((x,x))

array([[[1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4]]])

In [180]:
np.column_stack((x,x))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])